#!/bin/bash

state=${1?Usage HDMI [on/off] opt[left/right]}
pos=$2

# If position not defined, set to right
[[ -z $pos ]] && pos=right

# Select HDMI
hdmi_port=$(xrandr | grep HDMI | head -n 1 | awk '{print $1}')
# Select Principal Monitor
edp=$(xrandr | grep eDP | head -n 1 | awk '{print $1}')

connection=$(xrandr | grep $hdmi_port | head -n 1 | awk '{print $2}')

if [ $state == 'on' ]; then
    if [ $connection == 'disconnected' ]; then
        echo "Error: HDMI disconnected"
        exit 1
    else
        xrandr --output $hdmi_port --mode 1280x720 --${pos}-of $edp 
        xrandr --output $edp --primary
    fi
else
    xrandr --output $hdmi_port --off
fi
