#!/bin/bash

state=${1?Usage HDMI [on/off] opt[left/right] opt[primary]}
pos=$2

# If position not defined, set to right
[[ -z $pos ]] && pos=right

# Select HDMI
hdmi_port=$(xrandr | grep HDMI | head -n 1 | awk '{print $1}')
# Select Principal Monitor
edp=$(xrandr | grep eDP | head -n 1 | awk '{print $1}')

connection=$(xrandr | grep $hdmi_port | head -n 1 | awk '{print $2}')

if [ $state == 'on' ]; then
    if [ $connection == 'disconnected' ]; then
        echo "Error: HDMI disconnected"
        exit 1
    else
      if [ $pos == "above" ]; then
        xrandr --output $hdmi_port --mode 1366x768 --${pos} $edp 
        xrandr --output $hdmi_port --primary
      else 
        xrandr --output $hdmi_port --mode 1920x1080 --${pos}-of $edp 
        #xrandr --output $hdmi_port --mode 1366x768 --${pos}-of $edp 
        #xrandr --output $edp --primary
      fi
      wallpaper &
    fi
else
    xrandr --output $hdmi_port --off
fi
