#!/bin/bash

state=${1?Usage HDMI [on/off] opt[left/right]}
pos=$2

# If position not defined, set to right
[[ -z $pos ]] && pos=right

connection=$(xrandr | grep HDMI | awk '{print $2}')

if [ $state == 'on' ]; then
    if [ $connection == 'disconnected' ]; then
        echo "Error: HDMI disconnected"
        exit 1
    else
        xrandr --output HDMI-1 --mode 1366x768 --${pos}-of eDP-1
    fi
else
    xrandr --output HDMI-1 --off
fi
