#!/bin/bash

option=${1? Usage notify [OPTION]}

# OPTIONS:
    # battery_low
    # rest

# Set message for the option
[  $option == "battery_low"  ]  &&  title="BATERIA_BAJA!"
[  $option == "rest"  ]         &&  title="DESCANSAR"
[  $option == "shot"  ]         &&  title="SCREENSHOT"
[  $option == "other" ]         &&  title="${2}"; message="${3}"

# Sound
beep $option

# If no option matches, exit
[ "$title" == "" ] && exit 1;

# Send notification
notify-send --expire-time=3000 "$title" "$message"

exit 0
