#!/bin/bash

state=${1?"Usage: vol [up/down/mute] optional[sink_number]"}
sink=$2

# Check if pulse audio is installed
command -v pactl > /dev/null 2>&1 || { echo "Error: pulse audio isn't installed."; exit 1; }

# Choose first sink if not defined in parameters
[ -z $sink ] && sink=$(pactl list sinks | grep Sink | grep -oP '[0-9].*$' | head -n 1)

# Check if sink was defined, whether by user or the first found.
[ -z $sink ] && { echo "Error: no sinks to control"; exit 1; }

# Assign up or down volume (checking the limits and if sink really exist)
current=$(pacmd dump-volumes | grep "Sink $sink" | awk '{print $8}' | sed 's/\%//')
[ -z $current ] && { echo "Error: sink not found."; exit 1; }

if [ $state == "up" ]; then
    beep volume &
    if [ $current -le 95 ]; then 
        pactl set-sink-volume $sink +5%
    else
        pactl set-sink-volume $sink 100%
    fi

elif [ $state == "down" ]; then 
    beep volume &
    if [ $current -ge 5 ]; then
        pactl set-sink-volume $sink -5%
    else
        pactl set-sink-volume $sink 0%
    fi

elif [ $state == "mute" ]; then
    pactl set-sink-mute $sink toggle
    beep volume &
else
    echo "Error: Usage: vol [up/down/mute]"
    exit 1
fi

