#!/bin/bash

file=${1}
smooth=${2:-1}

if [ $smooth == 1 ]; then
    smooth="smooth acsplines"
else
    smooth=""
    echo $smooth
fi

gnuplotTmpDir=~/bin/gnuplot/tmp/

trap killgroup SIGINT

killgroup(){
  echo killing...
    kill 0
}


while [ 1 ]
do
    # Extract loss and accuracy values
    grep loss $file | awk '{print $11, $14, $17}' | cat -n > ~/bin/gnuplot/tmp/loss.data

    # Plot loss 
    gnuplot -e "set terminal png size 800,500; \
                set output '${gnuplotTmpDir}/loss.png';\
                set yrange [0.0005:0.09];\
                plot 
                    '${gnuplotTmpDir}/loss.data' using 1:2 every 100::1000 ${smooth} title 'Loss S1' with lines,
                    '${gnuplotTmpDir}/loss.data' using 1:3 every 100::1000 ${smooth} title 'Loss S2' with lines,
                    '${gnuplotTmpDir}/loss.data' using 1:4 every 100::1000 ${smooth} title 'Loss S3' with lines 
                " 
                # To smooth, use "smooth acsplines" befor "title" 
    grep 'Precision:' $file | awk '{print $4,$8,$12}' | cat -n > ~/bin/gnuplot/tmp/precision.data
    grep 'Recall:' $file | awk '{print $4,$8,$12}' | cat -n > ~/bin/gnuplot/tmp/recall.data

    # Plot Precision 
    gnuplot -e "set terminal png size 800,500; \
                set key right bottom; \
                set output '${gnuplotTmpDir}/precision.png';\
                set yrange [0:1];\
                plot 
                    '${gnuplotTmpDir}/precision.data' using 1:2 lw 2 ${smooth} title 'Precision S1' with lines,
                    '${gnuplotTmpDir}/precision.data' using 1:3 lw 2 ${smooth} title 'Precision S2' with lines,
                    '${gnuplotTmpDir}/precision.data' using 1:4 lw 2 ${smooth} title 'Precision S3' with lines'
                "
    # Plot Recall
    gnuplot -e "set terminal png size 800,500; \
                set key right bottom; \
                set output '${gnuplotTmpDir}/recall.png';\
                set yrange [0:1];\
                plot 
                    '${gnuplotTmpDir}/recall.data' using 1:2 lw 2 ${smooth} title 'Recall S1' with lines,
                    '${gnuplotTmpDir}/recall.data' using 1:3 lw 2 ${smooth} title 'Recall S2' with lines,
                    '${gnuplotTmpDir}/recall.data' using 1:4 lw 2 ${smooth} title 'Recall S3' with lines'
                "
    sleep 1
done &

sleep 1

feh --reload 0.5 $gnuplotTmpDir/loss.png &
feh --reload 2 $gnuplotTmpDir/precision.png &
feh --reload 2 $gnuplotTmpDir/recall.png &

wait
