#!/bin/bash

file=$1
gnuplotTmpDir=~/bin/gnuplot/tmp/

trap killgroup SIGINT

killgroup(){
  echo killing...
    kill 0
}


while [ 1 ]
do
    # Extract loss and accuracy values
    grep loss $file | awk '{print $11, $14, $17}' | cat -n > ~/bin/gnuplot/tmp/loss.data

    # Plot loss 
    gnuplot -e "set terminal png size 800,500; \
                set output '${gnuplotTmpDir}/loss.png';\
                plot 
                    '${gnuplotTmpDir}/loss.data' using 1:2 every ::50 smooth acsplines title 'Loss S1' with lines,
                    '${gnuplotTmpDir}/loss.data' using 1:3 every ::50 smooth acsplines title 'Loss S2' with lines,
                    '${gnuplotTmpDir}/loss.data' using 1:4 every ::50 smooth acsplines title 'Loss S3' with lines 
                " 
    grep 'Precision:' $file | awk '{print $4,$8,$12}' | cat -n > ~/bin/gnuplot/tmp/precision.data
    grep 'Recall:' $file | awk '{print $4,$8,$12}' | cat -n > ~/bin/gnuplot/tmp/recall.data

    # Plot Precision 
    gnuplot -e "set terminal png size 800,500; \
                set key right bottom; \
                set output '${gnuplotTmpDir}/precision.png';\
                plot 
                    '${gnuplotTmpDir}/precision.data' using 1:2 smooth mcsplines lw 2 title 'Precision S1' with lines,
                    '${gnuplotTmpDir}/precision.data' using 1:3 smooth mcsplines lw 2 title 'Precision S2' with lines,
                    '${gnuplotTmpDir}/precision.data' using 1:4 smooth mcsplines lw 2 title 'Precision S3' with lines'
                "
    # Plot Recall
    gnuplot -e "set terminal png size 800,500; \
                set key right bottom; \
                set output '${gnuplotTmpDir}/recall.png';\
                plot 
                    '${gnuplotTmpDir}/recall.data' using 1:2 smooth mcsplines lw 2 title 'Recall S1' with lines,
                    '${gnuplotTmpDir}/recall.data' using 1:3 smooth mcsplines lw 2 title 'Recall S2' with lines,
                    '${gnuplotTmpDir}/recall.data' using 1:4 smooth mcsplines lw 2 title 'Recall S3' with lines'
                "
    sleep 1
done &

sleep 1

feh --reload 0.5 $gnuplotTmpDir/loss.png &
feh --reload 2 $gnuplotTmpDir/precision.png &
feh --reload 2 $gnuplotTmpDir/recall.png &

wait
